### ISSUE TITLE
[Kotlin In Action] 1장 - 코틀린이란 무엇이며, 왜 필요한가?

### ISSUE THREAD

**Issue by 483759** [SSA-tudy/kotlin-study#1]
comment로 질문 달기 !

**Comment by 483759** [comment]
**서버 개발 측면에서** kotlin을 주 언어로 채택할만한 특장점이 무엇일까 ❓

**Comment by alb7979s** [comment]
1. 예시 주세요 현기증 난단 말이에요,,
    1-1. (41p 아래서 세번째 문단) "불변 데이터 구조를 사용하고 순수 함수를 그 데이터 구조에 적용한다면 다중 스레드 환경에서 같은 데이터를 여러 스레드가 변경할 수 없다." ?
    1-2. (41p 아래서 두번째 문단) "부수 효과(side effect)가 있는 함수는 그 함수를 실행할 때 필요한 전체 환경을 구성하는 준비 코드가 따로 필요하지만," ??

2. 질문 있어요~
    2-1. (45p 두번째 문단) 코틀린의 DSL 기능을 쓰면 JPA같은 ORM을 대체 가능하단 소린가요?
    2-2. (51p 마지막 문단) 그니까 타입 검사 생략해도 알아서 해준단 소리죠 코틀린님?
    2-3. (55p 1.5.3 대화형 셸) REPL을 쓰면 인터프리터 언어처럼 동작한다는 소리인가요? 또한 인터프리터 언어와의 차이점은?

3. 용어
    3-1. (45p 세번째 줄) DSL 기능
    3-2. (47p 여덟번째 줄) 인라이닝

**Comment by 483759** [comment]
![20211219_144306.jpg](https://user-images.githubusercontent.com/30489264/146665354-9b255210-b81c-488d-b853-d9d6b7e93b4f.jpg)

객체지향의 사실과 오해 149p)

여기에서는 메시지를 수신한 객체가 **실행 시간에 메서드를 선택하는 것**이 객체지향 언어가 절차지향 언어와 구분되는 차이점이라고 했는데

코틀린의 타입 추론 - 성능 부분을 보면 '런타임에 어떤 메서드를 호출할 지 결정하지 않아도 된다'라고 나와있습니다

그러면 코틀린은 일반적인 객체지향 특화 언어가 아닌걸까요 ??
