### ISSUE TITLE
[Kotlin In Action] 2장 - 코틀린 기초

### ISSUE THREAD

**Issue by alb7979s** [SSA-tudy/kotlin-study#2]

**Comment by 483759** [comment]
(64p) 타입으로 변수 선언을 시작하면 타입을 생략할 경우 식과 변수 선언을 구별할 수 없다

의 의미는?

**Comment by 483759** [comment]
(65p) 변수의 타입 추론 시 double 타입의 0을 할당하고 싶으면 0.0을 대입해야하나?

**Comment by 483759** [comment]
(66p) (자바에서는 final 키워드를 사용하면 변수 선언과 동시에 반드시 초기화를 해줘야 했지만) 코틀린은 val을 사용해서 변수를 선언할 때 선언과 대입을 분리해도 될까?

**Comment by 483759** [comment]
(69p) JavaBean 클래스란?

**Comment by 483759** [comment]
(72p) private 접근 제한자가 있어도 공개된 getter, setter를 모두 가지면 public과 다를 게 없다. 코틀린은 심지어 프로퍼티에 직접 접근할 수 있다. 캡슐화를 더 잘 구현하려면 어떻게 해야할까?

**Comment by 483759** [comment]
(60p)함수 파라미터에 var, val을 안 붙이면 어떻게 될까

**Comment by 483759** [comment]
(81p) when 구문을 사용할 때 setOf로 동등성을 판단한다고 했다.

1. 동등성 vs 동일성의 차이
2. Set collection이 아니어도 동등성으로 판단할까?
